### PR TITLE
JNI Android Support on Unrooted devices

### PR DESCRIPTION
**Pull request by CraigHutchinson**
Rebase of work on #874:

**This code implements connection and device listing on unrooted android devices, without requiring any user-provided java.**
This PR is usable now 🎉  

The java native interface library is used, which is always available when building on android, to do the sdk calls within libusb itself. The approach is modularised to aid expanding if new features are needed.
- Device enumeration by generating usb descriptors from the android sdk, which requires no user permission for this information.
- Detect if permission is needed when an unpermissioned device is opened, and perform the requestPermission call if necessary. This pops up a dialogue to the user asking if they will allow the connection.
   📓 Dispatching this request involves setting an action string on the intent for permission that the application can optionally subscribe to. The permission intent I dispatch has action string libusb.android.USB_PERMISSION.

The code only takes effect if the user provides their JNIEnv* or JavaVM* pointer via a new libusb option.

### CODE REVIEW

**Comment by CraigHutchinson** [comment]
Integrated Android support for device relisting https://github.com/xloem/libusb/pull/3

File: libusb/os/linux_usbfs.c [hunk 1]
```diff
@@ -935,51 +1192,64 @@ static int initialize_device(struct libusb_device *dev, uint8_t busnum,
 	/* cache descriptors in memory */
 	if (sysfs_dir) {
 		fd = open_sysfs_attr(ctx, sysfs_dir, "descriptors");
-	} else if (wrapped_fd < 0) {
```
Comment (CraigHutchinson) [inline libusb/os/linux_usbfs.c:938]: TODO: This change looks like could be an error during rebase?

File: libusb/os/linux_usbfs.c [hunk 2]
```diff
@@ -2765,6 +3059,12 @@ const struct usbi_os_backend usbi_backend = {
 	.caps = USBI_CAP_HAS_HID_ACCESS|USBI_CAP_SUPPORTS_DETACH_KERNEL_DRIVER,
 	.init = op_init,
 	.exit = op_exit,
+
+// Another option, disable hotplug all together
```
[the remark this answers is not in the document]
Comment (themarpe) [reply libusb/os/linux_usbfs.c:3063]: The comment refers to two options of implementing device relisting. By either modifying how hotplug works for Android case, or to modify it to not use hotplug, and rely on the "get_device_list". The latter did not work as expected, so I continued using modified hotplug which in turn works just like get_device_list does - upon "poll" it rescans.

**Comment by xloem** [comment]
I'm happy to have this replace #874 or merge and rebase it too, whatever works better for maintainers and contributors.

**Comment by CraigHutchinson** [comment]
@xloem I'm not sure but one option could be to force push this onto #874 then the conversation history is maintained while adding a cleaner set of commits? I would be happy to have this replace that pull also. Primarily its amazing work and it needs to get merged as has significant value.

Also, I would very much be in a position to aid/maintain for testing purposes.

Current identified issues(s):
1. [Minor] When device is being polled the USB Permissions prompt can occur multiple-times i.e. First prompt gives permission but a second prompt still is also pending and must therefore click 'ok' twice.

**Comment by mcuee** [comment]
For people who are interested in better Android support, please come here and post your review or success/fail testing results. Thanks.

**Comment by CraigHutchinson** [comment]
NOTE: Repository was now requires Signed-Commits so this PR has been rebased onto latest `libusb/master` and need verifying functionality

**Comment by tormodvolden** [comment]
Thanks for the rebasing work!

For information, the maintainers typically rebase any PR locally when merging, regardless of Signed-Commits or not, so just ignore the GitHub warning about this (dunno how to turn it off). However, before this PR can be merged it should ideally be worked down to the smallest number of commits that makes sense, so e.g. without fixups commits. If there are multiple authors it can be correct to have their commits separated for credit attribution, but minor fixups of other people's commit can be amended in-place and commented in the commit message.

**Comment by tormodvolden** [comment]
Now that we have libusb_init_context() in git master, it would be a good time to rebase this. The NO_DEVICE_DISCOVERY option should be set in the libusb_init_context() call.

File: libusb/os/linux_usbfs.h [hunk 3]
```diff
@@ -164,10 +164,12 @@ int linux_udev_start_event_monitor(void);
 int linux_udev_stop_event_monitor(void);
 int linux_udev_scan_devices(struct libusb_context *ctx);
 void linux_udev_hotplug_poll(void);
-#else
+#elif !defined(__ANDROID__)
 int linux_netlink_start_event_monitor(void);
 int linux_netlink_stop_event_monitor(void);
 void linux_netlink_hotplug_poll(void);
+#elif defined(__ANDROID__)
+void android_jni_hotplug_poll();
```
Comment (ila-embsys) [inline libusb/os/linux_usbfs.h:172]: I have an error here with NDK 25.2.9519653.

```shell
error: this function declaration is not a prototype
void android_jni_hotplug_poll();
                             ^
                              void
```

Should here be added 'void' inside brackets?

```suggestion
void android_jni_hotplug_poll(void);
```

File: libusb/os/linux_usbfs.h [hunk 4]
```diff
@@ -164,10 +164,12 @@ int linux_udev_start_event_monitor(void);
 int linux_udev_stop_event_monitor(void);
 int linux_udev_scan_devices(struct libusb_context *ctx);
 void linux_udev_hotplug_poll(void);
-#else
+#elif !defined(__ANDROID__)
 int linux_netlink_start_event_monitor(void);
 int linux_netlink_stop_event_monitor(void);
 void linux_netlink_hotplug_poll(void);
+#elif defined(__ANDROID__)
```
Comment (ila-embsys) [inline libusb/os/linux_usbfs.h:171]: These function prototypes inside the header file are wrapped in a conditional. Should the functions itself in the 'libusb/os/linux_netlink.c' file be wrapped out to the same conditional?

I have these errors if build with NDK 25.2.9519653.
```shell
libusb/os/linux_netlink.c:94:5: error: no previous prototype for function 'linux_netlink_start_event_monitor'
int linux_netlink_start_event_monitor(void)

libusb/os/linux_netlink.c:155:5 error: no previous prototype for function 'linux_netlink_stop_event_monitor'
int linux_netlink_stop_event_monitor(void)

libusb/os/linux_netlink.c:397:6 error: no previous prototype for function 'linux_netlink_hotplug_poll'
void linux_netlink_hotplug_poll(void)
```

Comment (xloem) [reply libusb/os/linux_usbfs.h:171]: I might consider removing the netlink file from the build entirely on line 37 of android/jni/libusb.mk, given android is an uncommon build target. I do not know netlink's potential role on rooted devices but it looks disabled as of now. Adding the proposed guards or changing build flags such that the condition is not an error would both also work.

**Comment by ankurvdev** [comment]
Its unclear to me whats preventing this from merging. Can someone summarize the action items needed ?

**Comment by mcuee** [comment]
> Its unclear to me whats preventing this from merging. Can someone summarize the action items needed ?

Need more reviews and tests. 

As of now it even has conflicts with the git repo.

**Comment by ben1681** [comment]
hello，I'm new here. Is there any Android demo using this branch? @CraigHutchinson @xloem

**Comment by CraigHutchinson** [comment]
Not entirely sure what sort of demo you mean. But the Libusb should work as per any other example as long as you provide the JNI for the context configurable iirc.

**Comment by CraigHutchinson** [comment]
I only rebased @xloem work but yes that is looking nearly there. Check the original PR for details which is linked on this rebase key bit is this (which I hope you gathered) 
> The code only takes effect if the user
> provides their JNIEnv* or JavaVM*
> pointer via a new libusb option.

I'm not at a PC nor working in this area for last year. As far as I recall the PR adds context options for setting these. It's upto your android code to choose where/how you get them but pass them in.

**Comment by ben1681** [comment]
@CraigHutchinson Thank you so much for your answer, I have read this today[#874](https://github.com/libusb/libusb/pull/874)， hard for me to fully understand by now. But finally I found out that @xloem has added an example to his libusb-android code[here](https://github.com/xloem/libusb/tree/android-test/android/native-app-example), the  guy I mentioned last time also wrote a[demo program](https://github.com/ibaiGorordo/libusbNativeAndroidTest/tree/main) for this example, just I didn't find and understand it yesterday.

**Comment by sebinho** [comment]
I am bringing this topic back to life because I am trying to implement something similar on an Android device but I cannot get it to work.
To give a bit of background, I did build an app using Kivy Framework (the app is written in Python). I am able to talk to USB devices if I access the JAVA classes directly from Python using usb4a (via pyjnius).

But now I would like to access USB devices using a native C++ SDK. This SDK is using libusb to talk to USB devices. I tried to port the code from [here](https://github.com/ibaiGorordo/libusbNativeAndroidTest/tree/main). But I get the following errors in my logcat:

```
10-16 19:34:12.742  6950  6950 I SDLThread: type=1400 audit(0.0:2428): avc: denied { read } for name="usb" dev="tmpfs" ino=334 scontext=u:r:untrusted_app:s0:c103,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=org.test.myapp
10-16 19:34:12.742  6950  6950 I SDLThread: type=1400 audit(0.0:2429): avc: denied { open } for path="/dev/bus/usb" dev="tmpfs" ino=334 scontext=u:r:untrusted_app:s0:c103,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=org.test.myapp
10-16 19:34:12.742  6950  6950 I SDLThread: type=1400 audit(0.0:2431): avc: denied { open } for path="/sys/bus/usb/devices" dev="sysfs" ino=24050 scontext=u:r:untrusted_app:s0:c103,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=1 app=org.test.myapp
```

It seems to be some kind of permission issue from SELinux, but not sure what I can do....

Can someone help? 
Is there any progress regarding libusb from a c++ project?

Many thanks in advance

**Comment by xloem** [comment]
- make sure the project you are porting succeeds for you alone
- make sure you are including something like [line 42](https://github.com/ibaiGorordo/libusbNativeAndroidTest/blob/5ed3249ff6b389208d5ff156cab0262c80a89356/app/src/main/cpp/main.cpp#L42) which provides the non-rooted device access

**Comment by sebinho** [comment]
@xloem, thanks for your reply. 
Indeed I decided to try and port the project untouched with Android Studio. I had to update some version numbers to match my device (it has Android 12 so I put SDK version to 31). I also had to update gradle as it was a very old version referenced.
Here is the updated `build.gradle`:
```
apply plugin: 'com.android.application'

android {
    namespace "com.example.myapp"

    compileSdkVersion 31

    defaultConfig {
        applicationId = 'com.example.libusbNativeAndroidTest'
        minSdkVersion 31
        targetSdkVersion 31
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            version '3.30.4'
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
}

configurations.all {
    resolutionStrategy { force 'androidx.work:work-runtime:2.7.1' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.startup:startup-runtime:1.1.1'
    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.work:work-runtime-ktx:2.7.1'
}
```

Not sure about the dependencies I added at the end of it, theses were trials to solve the issue I am facing. The issue I get when fetching logs with logcat is that the app shuts down as soon as it starts with following error:

```
10-18 17:27:04.939 10997 11023 F tiveAndroidTes: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethod called with pending exception java.lang.IllegalArgumentException: com.example.libusbNativeAndroidTest: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-18 17:27:04.939 10997 11023 F tiveAndroidTes: java_vm_ext.cc:579] Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-18 17:27:04.939 10997 11023 F tiveAndroidTes: java_vm_ext.cc:579]   at void android.app.PendingIntent.checkFlags(int, java.lang.String) (PendingIntent.java:375)
10-18 17:27:04.939 10997 11023 F tiveAndroidTes: java_vm_ext.cc:579]   at android.app.PendingIntent android.app.PendingIntent.getBroadcastAsUser(android.content.Context, int, android.content.Intent, int, android.os.UserHandle) (PendingIntent.java:645)
10-18 17:27:04.939 10997 11023 F tiveAndroidTes: java_vm_ext.cc:579]   at android.app.PendingIntent android.app.PendingIntent.getBroadcast(android.content.Context, int, android.content.Intent, int) (PendingIntent.java:632)
```

The message seems to claim that we have to use FLAG_IMMUTABLE or FLAG_MUTABLE, but these are parameters to be set inside JAVA source code and this project only has a C++ file.

Any idea on how to solve this?
Many thanks

**Comment by sebinho** [comment]
ok, so I was able to get one step further. I had to modify the source code of the updated libusb in `linux_android_jni.c`. This is because from API version 31 onwards, we have to use FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. 
So I changed this:
```
	/* PendingIntent permission_intent =
		PendingIntent.getBroadcast(application_context, 0, intent, 0); */
	permission_intent =
		(*jni_env)->CallStaticObjectMethod(jni_env,
			jni->PendingIntent, jni->PendingIntent__getBroadcast,
			jni->application_context, 0, intent, 0);
```

into this:

```
	/* PendingIntent permission_intent =
		PendingIntent.getBroadcast(application_context, 0, intent, 0); */
	permission_intent =
		(*jni_env)->CallStaticObjectMethod(jni_env,
			jni->PendingIntent, jni->PendingIntent__getBroadcast,
			jni->application_context, 0, intent, 33554432);
```

33554432 is the value for FLAG_MUTABLE, see here: https://developer.android.com/reference/android/app/PendingIntent#FLAG_MUTABLE

Now the problem I have is that the application does not do anything regarding USB devices. If my understanding is correct, when launching the app it should print a list of the USB devices connected but nothing happens.
I put some debug log messages and it seems that the function `void android_main(struct android_app * state)` is never entered...

Here is the log, if it can help.

```
10-18 19:10:00.291   596   610 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.example.libusbNativeAndroidTest/android.app.NativeActivity bnds=[1276,301][1592,449]} from uid 10079
10-18 19:10:00.308   596   625 I ActivityManager: Start proc 15935:com.example.libusbNativeAndroidTest/u0a111 for pre-top-activity {com.example.libusbNativeAndroidTest/android.app.NativeActivity}
10-18 19:10:00.312   397   397 D android.hardware.graphics.allocator@4.0-service: got new private_handle_t instance for buffer 'ViewRootImpl[libusbNativeAndroidTest]#140(BLAST Consumer)140'. share_fd : 9, share_attr_fd : 10, width : 1920, height : 1080, req_format : 0x1, producer_usage : 0xb00, consumer_usage : 0xb00, , stride : 0, alloc_format : 1, size : 8486912, layer_count : 1
10-18 19:10:00.312   397   397 D android.hardware.graphics.allocator@4.0-service: got new private_handle_t instance for buffer 'ViewRootImpl[libusbNativeAndroidTest]#140(BLAST Consumer)140'. share_fd : 9, share_attr_fd : 10, width : 1920, height : 1080, req_format : 0x1, producer_usage : 0xb00, consumer_usage : 0xb00, , stride : 0, alloc_format : 1, size : 8486912, layer_count : 1
10-18 19:10:00.312   397   397 D android.hardware.graphics.allocator@4.0-service: got new private_handle_t instance for buffer 'ViewRootImpl[libusbNativeAndroidTest]#140(BLAST Consumer)140'. share_fd : 9, share_attr_fd : 10, width : 1920, height : 1080, req_format : 0x1, producer_usage : 0xb00, consumer_usage : 0xb00, , stride : 0, alloc_format : 1, size : 8486912, layer_count : 1
10-18 19:10:00.346 15935 15935 V GraphicsEnvironment: ANGLE Developer option for 'com.example.libusbNativeAndroidTest' set to: 'default'
10-18 19:10:00.346 15935 15935 V GraphicsEnvironment: ANGLE GameManagerService for com.example.libusbNativeAndroidTest: false
10-18 19:10:00.409 15935 15935 I tiveAndroidTest: type=1400 audit(0.0:9627): avc: denied { read } for name="usb" dev="tmpfs" ino=357 scontext=u:r:untrusted_app:s0:c111,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=com.example.libusbNativeAndroidTest
10-18 19:10:00.409 15935 15935 I tiveAndroidTest: type=1400 audit(0.0:9628): avc: denied { open } for path="/dev/bus/usb" dev="tmpfs" ino=357 scontext=u:r:untrusted_app:s0:c111,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=com.example.libusbNativeAndroidTest
10-18 19:10:00.412 15935 15935 I Thread-2: type=1400 audit(0.0:9629): avc: denied { search } for name="usb" dev="tmpfs" ino=357 scontext=u:r:untrusted_app:s0:c111,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=com.example.libusbNativeAndroidTest
10-18 19:10:10.333   596   618 V WindowManager: getPackagePerformanceMode -- ComponentInfo{com.example.libusbNativeAndroidTest/android.app.NativeActivity} -- com.example.libusbNativeAndroidTest -- mode=0
```

any idea @xloem ?
Thx

**Comment by xloem** [comment]
Does anybody have a working example using one of these pull requests? I imagine it would be for an older libusb and an older android sdk.

If new to the code, it might probably make sense to forward-port something working one version at a time.

I might have time to help iterate issues if tagged elsewhere (maybe drop a link here) to not clog this thread too much. I was excited to do the first coding for this work but am stuck on iOS myself right now.

**Comment by ila-embsys** [comment]
> Does anybody have a working example using one of these pull requests?

I had a working demo application that was connecting to AR glasses by libusb version from exactly this MR. This demo is an android application based on 'NativeActivity' with c++ code and CMake project.

[This is a link](https://github.com/ila-embsys/monado_demo_xrgears/pull/1) where I saved code changes and description about what were necessary to port the demo application. The description is not fully about libusb usage, though the libusb related parts still could be useful.

As I see now, the important steps I did in the code were next:

1. [Create libusb context](https://github.com/ila-embsys/monado_demo_xrgears/pull/1/files#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2R654-R657) with set option `LIBUSB_OPTION_ANDROID_JAVAVM`
```cpp
libusb_context *ctx;
libusb_set_option(ctx, LIBUSB_OPTION_ANDROID_JAVAVM, app->activity->vm);
libusb_init(&ctx);
```

2. [Set USB permission](https://github.com/ila-embsys/monado_demo_xrgears/pull/1/files#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdR20) in Android manifest
```xml
<uses-permission android:name="android.hardware.usb.host" />
```

3. [Link application with libusb](https://github.com/ila-embsys/monado_demo_xrgears/pull/1/files#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4R68) prebuilt from this MR

```cmake
find_package(Libusb1 REQUIRED MODULE)

target_include_directories(xrgears PUBLIC ${LIBUSB1_INCLUDE_DIRS})
target_link_libraries(xrgears ${LIBUSB1_LIBRARIES})
```

Hope this information would be helpful.

**Comment by calvin2021y** [comment]
@CraigHutchinson 

more than 3 years,  the patch not able to work with ` libusb 1.0.27`.  any plan to update or merge this?

**Comment by Lorenzooone** [comment]
Just wanted to drop by to say that I have used this successfully on Android, when targeting Android API 31.
I have used jagheterfredrik's branch (which currently has a PR going into CraigHutchinson's branch to fix a couple of compilation issues with newer NDKs), and it works flawlessly!

The only real "issue" is that it seems to be unable to compile for armeabi-v7a with the lowest Android API (16) due to it missing some timerfd functions, an error which does not happen when using regular libusb.
The fix to that is simply targeting a higher Android API (I did 31 for my setup since that is what the docker is based on).

Besides that, it really is as simple as giving the JVM pointer to libusb when you init the library. And then, it just works.

**Comment by YFogRain** [comment]
我倒是有个其他方案，不使用jni反调安卓的方法。
1. 使用usbmanager获取到usbdevice的文件描述符
2. 传递这个fd到native层，native层新增get_Device_with_fd的方法，将fd赋值给底层的struct缓存
3. 打开设备时，通过这个缓存的fd，来赋值给对应的配置
因为fd已经申请到权限，所以，使用ioctl跟linux底层交互时，这个fd就能够正常通讯
。现在问题是，我使用当前方案，在安卓上表现正常，但是在鸿蒙上，因为获取当前fd绑定的驱动问题，会导致执行IOCTL_USBFS_IOCTL这个方法在没有驱动绑定时造成ANR问题，当前在研究解决方案

**Comment by mcuee** [comment]
@CraigHutchinson 

Just wondering if you can update this PR to resolve the conflicts with master. Thanks.

**Comment by kubaraczkowski-spectricity** [comment]
Hi all,

Excellent work, we've used libusb as Android USB solution for years now, this could make it even easier!

However, it seems that Android 15 breaks the whole game... It seems (from tests and e.g. Gemini) that it introduces stricter SELinux policies that disallow operations on the USB devices from Native libs. ONLY SDK (Java) transfers are allowed.

Could somebody confirm this perhaps?

**Comment by bearsh** [comment]
> However, it seems that Android 15 breaks the whole game... It seems (from tests and e.g. Gemini) that it introduces stricter SELinux policies that disallow operations on the USB devices from Native libs. ONLY SDK (Java) transfers are allowed.
> 
> Could somebody confirm this perhaps?

I have an application (Kotlin (UI) -> golang (high-level driver) -> libusb) which works on my Pixel with Android 16. I open the usb handle through the Kontlin API, perhaps this makes the difference...

**Comment by Lorenzooone** [comment]
> Hi all,
> 
> Excellent work, we've used libusb as Android USB solution for years now, this could make it even easier!
> 
> However, it seems that Android 15 breaks the whole game... It seems (from tests and e.g. Gemini) that it introduces stricter SELinux policies that disallow operations on the USB devices from Native libs. ONLY SDK (Java) transfers are allowed.
> 
> Could somebody confirm this perhaps?

I have an Android 15 phone, and this fork of libusb works on it.

All I do is this: https://github.com/Lorenzooone/cc3dsfs/blob/79116a27fdf56b3f73443c4a2c1450ee6f1dfa29/source/CaptureDeviceSpecific/usb_generic.cpp#L20

**Comment by kubaraczkowski-spectricity** [comment]
Thanks for confirming! Indeed, it was a USB hub issue, and Gemini was hallucinating the root cause...

NICE!

**Comment by mcuee** [comment]
Just wondering if anyone can work on this to resolve the conflicts. Thanks.

Any guide how to test libusb on non-rooted Android devices here? 

I am able to carry out tests on most of the libusb supported platforms, like Linux, Windows, macOS, OpenBSD, NetBSD, WebAssembly, Haiku and illumos (OpenSolaris based). 

But I have never been able to get libusb to work on Android (a total Android newbie here).

I tried termux-usb but it does not work.

* https://github.com/pyusb/pyusb/pull/287
* https://wiki.termux.com/wiki/Termux-usb

```
~/test $ termux-usb -l 
[
  "/dev/bus/usb/001/006",
  "/dev/bus/usb/001/005",
  "/dev/bus/usb/001/003"
]
~/test $ termux-usb -e ./usbtest /dev/bus/usb/001/003Permission denied.
~/test $ termux-usb -e ./usbtest /dev/bus/usb/001/005Permission denied.
~/test $ termux-usb -e ./usbtest /dev/bus/usb/001/006Permission denied.
```

**Comment by mcuee** [comment]
There is fork here with two commits ahead of this PR.
https://github.com/jagheterfredrik/libusb/tree/android-rebase-2022-07

**Comment by mcuee** [comment]
It would be good if somebody can resolve the conflicts and then latest github action will generate the binaries, now that there is an official libusb NDK github action here.
https://github.com/libusb/libusb/blob/master/.github/workflows/android.yml

You can download the build binaries from each run.
Example: latest run on the master branch (not this PR).
https://github.com/libusb/libusb/actions/runs/26518291496

**Comment by Lorenzooone** [comment]
As I used this PR more, I realized that something that needs to be implemented is a function to check if the device has permission that can be accessed from the libusb interface.
That, or the function to ask for permission for a device should be exposed in the libusb interface.

As it is now, in this PR there is no way to know whether the permission has been granted or not without asking again to access the device (which will spawn a second/third/fourth/... request for permission, creating a queue for the user, and a very bad user experience).

That, or I was unable to find the way to check this.

Input on the matter is welcome. As to how to do it or how the interface should be exposed.

**Comment by Youw** [comment]
> Input on the matter is welcome. As to how to do it or how the interface should be exposed.

I believe you're right, there is no good way for now to make a good UX on the permissions patter.
Based on my experience with Android projects, we'd need to introduce at least two additional API functions:
- one to get a list of required permissions for libusb to function (so user application code can request those explicitly)
- a function to explicitly request those permissions, independently from libusb init/enumerate
