### ISSUE TITLE
Can't link against 1.0.25 in OS X Monterey

### ISSUE THREAD

**Issue by majenkotech** [libusb/libusb#1072]
[Code](https://github.com/majenkotech/pic32prog-autotools) that works perfectly on 1.0.24 in Monterey won't work with 1.0.25:

```
Undefined symbols for architecture x86_64:
  "_SecTaskCopyValueForEntitlement", referenced from:
      _darwin_detach_kernel_driver in libusb-1.0.a(darwin_usb.o)
  "_SecTaskCreateFromSelf", referenced from:
      _darwin_detach_kernel_driver in libusb-1.0.a(darwin_usb.o)
ld: symbol(s) not found for architecture x86_64
```

Darwin Matts-iMac-Pro 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

**Comment by majenkotech** [comment]
Fix: need to now add `-framework Security`

**Comment by zhangguofu** [comment]
May I ask where to add -framework Security?

**Comment by seanm** [comment]
Security.framework is already part of libusb.xcodeproj. How are you building?

**Comment by zhangguofu** [comment]
> Security.framework is already part of libusb.xcodeproj. How are you building?

I'm using cmake & make to do the jod, and it has been fixed as the snap-shot shows below:
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/63c1c60a-6c08-4fc1-ad86-28bab966fb7e">

by the way, why the libusb latest version is not adopted for macOS platform? do you know the story behind?

**Comment by mcuee** [comment]
Not so sure what you mean.

Homebrew has libusb 1.0.27.
https://github.com/Homebrew/homebrew-core/blob/ce0f397aaa10126e9c962f87ed546f07c33eac77/Formula/lib/libusb.rb

Same for MacPorts.
https://ports.macports.org/port/libusb/details/

**Comment by seanm** [comment]
> by the way, why the libusb latest version is not adopted for macOS platform? do you know the story behind?

I'm not sure what you mean here. (I suspect English in not your first language...)

For me at least, libusb works on all versions of macOS, at least for the things I use it for.

Do you mean why does macOS itself not include libusb?  Apple rarely includes third party software, so that's not surprising, and is unlikely to change.
