### PR TITLE
Fix build failure on Mac OS X 10.7

### LINKED ISSUE #410: Build failure on OS X 10.7: use of undeclared identifier 'kUSBDeviceSpeedSuper'
libusb 1.0.22 fails to build on OS X 10.7 with:

```
os/darwin_usb.c:1043:10: error: use of undeclared identifier 'kUSBDeviceSpeedSuper'; did you mean 'kUSBDeviceSpeedFull'?
    case kUSBDeviceSpeedSuper: dev->speed = LIBUSB_SPEED_SUPER; break;
         ^~~~~~~~~~~~~~~~~~~~
         kUSBDeviceSpeedFull
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:899:9: note: 'kUSBDeviceSpeedFull' declared here
        kUSBDeviceSpeedFull             = 1,
        ^
```

Here is a [full build log](https://build.macports.org/builders/ports-10.7_x86_64_legacy-builder/builds/61294/steps/install-port/logs/stdio) from the MacPorts project's automated build system.

This is a new problem for 1.0.22; 1.0.21 didn't have this problem.

It's caused by e4851c38946560ac0fe3eeea848b37c264b4a9c8 which changes the restriction on when `kUSBDeviceSpeedSuper` is used to the condition `MAC_OS_X_VERSION_MAX_ALLOWED >= 1070`. [Apple documentation](https://developer.apple.com/documentation/iokit/1425357-usbdevicespeed/kusbdevicespeedsuper) says `kUSBDeviceSpeedSuper` was introduced in OS X 10.7, but the documentation is apparently incorrect. According to [a SourceForge mailing list post](https://sourceforge.net/p/libusb/mailman/message/30467617/), it was actually introduced in 10.8. libusb 1.0.22 does build successfully in MacPorts on OS X 10.8. So I would change the condition to `MAC_OS_X_VERSION_MAX_ALLOWED >= 1080`.

### PR DESCRIPTION
**Pull request by ryandesign**
Apple documentation says kUSBDeviceSpeedSuper is available in 10.7 and
later but in fact it is only defined in the 10.8 SDK and later.

Closes #410

### CODE REVIEW

**Comment by seanm** [comment]
lgtm

**Comment by mcuee** [comment]
Ack.

**Review by mcuee — APPROVED** [review]
